// Generated by CoffeeScript 1.10.0
(function() {
  var AtomJournal, AtomJournalView, CompositeDisposable;

  AtomJournalView = require('./atom-journal-view');

  CompositeDisposable = require('atom').CompositeDisposable;

  module.exports = AtomJournal = {
    atomJournalView: null,
    modalPanel: null,
    subscriptions: null,
    activate: function(state) {
      this.atomJournalView = new AtomJournalView(state.atomJournalViewState);
      this.atomJournalView.setDate(new Date());
      this.modalPanel = atom.workspace.addTopPanel({
        item: this.atomJournalView.getElement(),
        visible: false
      });
      this.subscriptions = new CompositeDisposable;
      return this.subscriptions.add(atom.commands.add('atom-workspace', {
        'atom-journal:toggle': (function(_this) {
          return function() {
            return _this.toggle();
          };
        })(this)
      }));
    },
    deactivate: function() {
      this.modalPanel.destroy();
      this.subscriptions.dispose();
      return this.atomJournalView.destroy();
    },
    serialize: function() {
      return {
        atomJournalViewState: this.atomJournalView.serialize()
      };
    },
    toggle: function() {
      console.log('AtomJournal was toggled!');
      if (this.modalPanel.isVisible()) {
        return this.modalPanel.hide();
      } else {
        return this.modalPanel.show();
      }
    }
  };

}).call(this);
